// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXuKjMpPhOF2l3UlidHQGPoIrJTTJ85Tw',
    appId: '1:507971623473:web:2d6eec698b8fbc72395310',
    messagingSenderId: '507971623473',
    projectId: 'chatt-app-a861d',
    authDomain: 'chatt-app-a861d.firebaseapp.com',
    storageBucket: 'chatt-app-a861d.appspot.com',
    measurementId: 'G-FXNFNFVRF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEpQNtah_6FJSNcRYlnM4o1LvKZKONtA',
    appId: '1:507971623473:android:27f0b04ca6534730395310',
    messagingSenderId: '507971623473',
    projectId: 'chatt-app-a861d',
    storageBucket: 'chatt-app-a861d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBierYjsLiOltpk35lAKvxlJhrYaCjnDC0',
    appId: '1:507971623473:ios:f6e1423cd75f05b4395310',
    messagingSenderId: '507971623473',
    projectId: 'chatt-app-a861d',
    storageBucket: 'chatt-app-a861d.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBierYjsLiOltpk35lAKvxlJhrYaCjnDC0',
    appId: '1:507971623473:ios:f6e1423cd75f05b4395310',
    messagingSenderId: '507971623473',
    projectId: 'chatt-app-a861d',
    storageBucket: 'chatt-app-a861d.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXuKjMpPhOF2l3UlidHQGPoIrJTTJ85Tw',
    appId: '1:507971623473:web:71d4473a923b8ce2395310',
    messagingSenderId: '507971623473',
    projectId: 'chatt-app-a861d',
    authDomain: 'chatt-app-a861d.firebaseapp.com',
    storageBucket: 'chatt-app-a861d.appspot.com',
    measurementId: 'G-BS0J316PBG',
  );

}